# Configuration de la base de données
spring.datasource.url=jdbc:mysql://localhost:3306/biblio
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Désactiver la mise à jour automatique du schéma
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# Configuration pour éviter les problèmes de classloader
spring.datasource.hikari.register-mbeans=false
spring.jpa.open-in-view=false

# Configuration détaillée des logs
logging.level.org.springframework=INFO
logging.level.org.springframework.web=INFO
logging.level.org.hibernate=ERROR

# Configuration pour logger les erreurs dans un fichier
logging.file.name=app.log

# Éviter les warnings de TLD scanning
logging.level.org.apache.jasper.servlet.TldScanner=ERROR